name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'
      
env:
  PROJECT_ID: 'shrekchat'
  REGION: 'us-central1'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Authenticate Docker with GCloud
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Environment variables
        run: |-
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> ./.env
          echo "SESSION_MAX_AGE=${{ secrets.SESSION_MAX_AGE }}" >> ./.env

      - name: Build and Push
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/webchat/images"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy shrekchat \
            --image="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/webchat/images" \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated
